/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1002;


import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class CircleTest {
	@Test
	public void test2() {
		Circle c1 = new Circle(2.00);
		double expected = 12.5664;
		double actual = c1.getArea();
		assertEquals(expected, actual, 0.0001);
	}
	
	@Test
	public void test100Dot64() {
		Circle c1 = new Circle(100.64);
		double expected = 31819.3103;
		double actual = c1.getArea();
		assertEquals(expected, actual, 0.0001);
	}
	@Test
	public void test150() {
		Circle c1 = new Circle(150.00);
		double expected = 70685.7750;
		double actual = c1.getArea();
		assertEquals(expected, actual, 0.0001);
	}
}
