/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1002;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class RetangleTest {
	@Test
	public void DeveRetornarAreaComBase3Altura4() {
		Retangle r1 = new Retangle(3.0, 4.0);
		double expected = 12.000;
		double actual = r1.getArea();
		assertEquals(expected, actual, 0.001);
	}

	@Test
	public void DeveRetornarAreaComBase12Dot7Altura10Dot4() {
		Retangle r2 = new Retangle(12.7, 10.4);
		double expected = 132.080;
		double actual = r2.getArea();
		assertEquals(expected, actual, 0.001);
	}
}