/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1002;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class SquareTest {

	@Test
	public void DeveRetornarAreaComLado4() {
		Square s1 = new Square(4.00);
		double expected = 16.000;
		double actual = s1.getArea();
		assertEquals(expected, actual, 0.001);
	}

	@Test
	public void DeveRetornarAreaComLado10Dot4() {
		Square s1 = new Square(10.4);
		double expected = 108.160;
		double actual = s1.getArea();
		assertEquals(expected, actual, 0.001);
	}

}