/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1002;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class TriangleTest {
	@Test
	public void DeveRetornarAreaComBase3Altura5Dot2() {
		Triangle t1 = new Triangle(3.0, 5.2);
		double expected = 7.800;
		double actual = t1.getArea();
		assertEquals(expected, actual, 0.001);
	}

	@Test
	public void DeveRetornarAreaComBase12Dot7Altura10Dot4() {
		Triangle t1 = new Triangle(12.7, 15.2);
		double expected = 96.520;
		double actual = t1.getArea();
		assertEquals(expected, actual, 0.001);
	}
}